#!/bin/sh
#
### BEGIN INIT INFO
# Provides: labwc
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
LABWC_USER=diya
LABWC_CONFDIR="/etc/labwc"
if test -e "/home/$LABWC_USER/.config/labwc" ; then
    LABWC_CONFDIR="/home/$LABWC_USER/.config/labwc"
fi

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

read CMDLINE < /proc/cmdline
for x in $CMDLINE; do
        case $x in
        labwc=false)
            echo "labwc disabled"
            exit 0;
            ;;
        esac
done

case "$1" in
  start)
        . /etc/profile
        su - $LABWC_USER -c "labwc -C  $LABWC_CONFDIR" &
  ;;

  stop)
        echo "Stopping Weston"
        killproc labwc
  ;;

  restart)
    $0 stop
    sleep 1
    $0 start
  ;;

  *)
    echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
