#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="Custom configuration"
. /etc/profile

case "$1" in
    start)
        echo -n "Start $DESC: "
        # for some reason the LCD backlight is turned off
        # need to turn it on manually
        echo  0 > /sys/class/backlight/backlight/bl_power

        cat << EOF > /boot/extraconfig.txt
# initramfs recovery-${MACHINE}.cpio.gz followkernel
EOF
    ;;

    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start}" >&2
        exit 1
    ;;
esac

exit 0